### PR TITLE
add classes into transport

### PR DESCRIPTION
**Pull request by y-nk**
This small contribution is a very huge need for me. It allows to compute classes on the `<portal>` side and pass them to the `<portal-target />` side.

This allows a use-case such as showing or hiding the portal container : 

```
<portal to="modals" :class="iWantToShowMyModal ? 'show' : 'hide'">
  <my-modal v-if="iWantToShowMyModal" />
</portal>

...

<portal-target name="modals" class="modal-container backdrop" />
```

### CODE REVIEW

**Comment by LinusBorg** [comment]
Hey, thanks for this PR :)

I think this is a good idea, and think we can add this. 

But concerning details, I'm pondering wether a separate prop for this would be better, as opposed to using the class attribute as you do now.

Reasoning:  

* The `<portal>` can be `disabled`, which means its content will be rendered in-place. 
* Someone may apply some styles to the wrapper element created by the portal , but *not* to the `<portal-target>` when its `enabled` again.

So I think using a separate prop (e.g. `classForTarget`) would make more sense?

**Comment by LinusBorg** [comment]
> I'm thinking how to handle clicks on the portal-target from the "portal/modal-author" point of view, so I could actually handle this event properly.

This doesn't really feel right to me. in my mind, the portal-target container was always just a container.

This PR would allow to add classes to it, which makes it more than just a container, of course, but only in a limited, static way. Bringing event listeners etc. into it seems to overblow it, in my mind.

I would rather imagine that listeners are applied to either the portal content or elements wrapping `<portal-target>` - events bubble up, after all.

**Comment by y-nk** [comment]
@LinusBorg any update on that PR 😅 ?

**Comment by LinusBorg** [comment]
Ok so Ive been changing my mind, reworkgin the whole setup will take too long, so I want to push a last version out before this. Already fixed two bugs, and would like to merge this.

Would you feel able to add tests? those are still missing...

**Comment by LinusBorg** [comment]
added them myself while a was at it.

**Pull request merged**
