### PR TITLE
fix(typo): fixed advanced syntax typo

### PR DESCRIPTION
**Pull request by codebender828**
Documentation typo fix for advanced syntax

### CODE REVIEW

**Comment by LinusBorg** [comment]
oh, that was actually against the wrong branch - `next`. That's stale and already merged into `develop`

**Comment by codebender828** [comment]
Hi @LinusBorg Oh! Haha. Sorry about that. What branch would you advise me to work against?

**Comment by codebender828** [comment]
I did it all from github so I thought it would be opened against the default branch

**Comment by LinusBorg** [comment]
default branch is `develop`, you must have done this by mistake somehow.

Feel free to open a new PR against `develop` if the error exists there as well. :)

**Comment by codebender828** [comment]
No worries 👍🏽. Thanks!

**Pull request merged**
